name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: poetry install
    
    - name: Run tests
      run: poetry run pytest tests/ -v

    - name: Test CLI - Help command
      run: |
        poetry run python main.py --help
        poetry run python main.py extract --help
        poetry run python main.py train --help
        poetry run python main.py stats --help
    
    - name: Test CLI stats
      run: poetry run python main.py stats
    
    - name: Test CLI extraction
      run: |
        echo "Machine learning is AI. Deep learning uses neural networks." > test_input.txt
        poetry run python main.py extract -i test_input.txt -t 5
        rm test_input.txt   

    